name: check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install
        run: pip install -r requirements.txt
      - name: check imports
        run:  isort --check .
      - name: check formatting
        run:  black --check .
      - name: run linter
        run:  pylint --recursive y .
